# Generated by Django 4.2.16 on 2025-03-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgname', models.CharField(max_length=254)),
                ('address1', models.CharField(max_length=40)),
                ('address2', models.CharField(blank=True, max_length=40, null=True)),
                ('town', models.CharField(max_length=40)),
                ('postcode', models.CharField(max_length=8)),
                ('county', models.CharField(default='East Sussex', max_length=20)),
                ('telephone', models.CharField(max_length=14, null=True)),
                ('contact_name', models.CharField(max_length=254)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
