# Generated by Django 4.2.16 on 2025-03-10 22:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=254)),
                ('address1', models.CharField(max_length=40)),
                ('address2', models.CharField(blank=True, max_length=40, null=True)),
                ('town', models.CharField(max_length=40)),
                ('postcode', models.CharField(max_length=8)),
                ('county', models.CharField(default='East Sussex', max_length=20)),
                ('telephone', models.CharField(max_length=14, null=True)),
                ('max_occupants', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)])),
                ('gas_safety', models.BooleanField(blank=True, default=False)),
                ('gas_safety_date', models.DateField()),
            ],
        ),
    ]
