# Generated by Django 4.2.16 on 2025-03-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0003_remove_category_friendly_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=254),
        ),
    ]
