# Generated by Django 4.2.16 on 2025-03-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_friendly_name'),
        ('host', '0005_delete_category_alter_host_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='gas_safety',
        ),
        migrations.AlterField(
            model_name='host',
            name='categories',
            field=models.ManyToManyField(blank=True, to='category.category'),
        ),
        migrations.AlterField(
            model_name='host',
            name='gas_safety_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
