# Generated by Django 4.2.16 on 2025-03-06 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_is_approved_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MaxValueValidator(5, message="Glad you're so pleased but Maximum score is 5!"), django.core.validators.MinValueValidator(1, message='Score must be 1 or more - Be Generous!'), django.core.validators.StepValueValidator(0.1, message='Scores are in one decimal point only')]),
        ),
    ]
