# Generated by Django 4.2.16 on 2025-03-15 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
        ('teamlead', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamlead',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org', to='organisation.organisation'),
        ),
        migrations.AlterField(
            model_name='teamlead',
            name='mobile',
            field=models.CharField(max_length=12),
        ),
    ]
