# Generated by Django 4.2.16 on 2025-03-10 22:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=254, null=True)),
                ('last_name', models.CharField(max_length=254, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('is_adult', models.BooleanField(default=True, null=True)),
                ('is_child', models.BooleanField(default=False, null=True)),
                ('child_age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(17), django.core.validators.MinValueValidator(1)])),
                ('valid_dbs', models.BooleanField(default=True, null=True)),
                ('dbs_date', models.DateField()),
            ],
        ),
    ]
