# Generated by Django 4.2.16 on 2025-03-11 23:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_members_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='child_age',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(17), django.core.validators.MinValueValidator(0)]),
        ),
    ]
