# Generated by Django 4.2.16 on 2025-03-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_members_child_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unsure')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
