# Generated by Django 4.2.16 on 2025-03-15 20:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_members_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='child_age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(17), django.core.validators.MinValueValidator(0)]),
        ),
    ]
