# Generated by Django 4.2.16 on 2025-03-16 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_members_child_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='valid_dbs',
        ),
    ]
