# Generated by Django 4.2.16 on 2025-03-11 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeperiod', '0003_remove_timeperiod_pupil'),
        ('pupil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeperiod', to='timeperiod.timeperiod'),
        ),
    ]
