# Generated by Django 4.2.16 on 2025-03-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupil', '0002_pupil_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unsure')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
